In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,10,(2,3))
x

array([[6, 9, 3],
       [3, 4, 4]])

In [3]:
y = np.random.randint(1,10,(2,3))
y

array([[5, 2, 7],
       [5, 8, 5]])

In [4]:
x+y

array([[11, 11, 10],
       [ 8, 12,  9]])

In [5]:
x-y

array([[ 1,  7, -4],
       [-2, -4, -1]])

In [6]:
x*y

array([[30, 18, 21],
       [15, 32, 20]])

In [7]:
x/y

array([[1.2       , 4.5       , 0.42857143],
       [0.6       , 0.5       , 0.8       ]])

In [8]:
x//y

array([[1, 4, 0],
       [0, 0, 0]])

In [10]:
x**y

array([[ 7776,    81,  2187],
       [  243, 65536,  1024]])

In [11]:
x

array([[6, 9, 3],
       [3, 4, 4]])

In [12]:
y

array([[5, 2, 7],
       [5, 8, 5]])

In [24]:
# cross product (shape of both matrix must be same)
x*y

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [83]:
x = np.random.randint(1,10,(2,3))
x

array([[5, 3, 9],
       [8, 7, 9]])

In [82]:
y = np.random.randint(1,10,(3,2))
y

array([[2, 1],
       [8, 3],
       [9, 9]])

In [86]:
print(10+24+81  , 5+9+81)

16+56+81  , 8+21+81

115 95


(153, 110)

In [87]:
# dot product

In [88]:
x@y

array([[115,  95],
       [153, 110]])

In [62]:
# valid - 

# matrix 1 - R1 X C1  
# matrix 2- R2 X C2 

# if C1 == R2 then only we can perform dot product

# output = R1 X C2

In [64]:
x = np.random.randint(1,10,(3,2))
x

array([[4, 9],
       [7, 8],
       [6, 7]])

In [69]:
y = np.random.randint(1,10,(2,5))
y

array([[8, 5, 2, 5, 6],
       [6, 1, 5, 7, 9]])

In [70]:
x@y

array([[126,  54,  63, 108, 135],
       [ 56,  24,  28,  48,  60],
       [ 52,  16,  34,  52,  66]])

In [71]:
# concatenation

In [89]:
x = np.random.randint(1,10,5)
x

array([8, 2, 6, 5, 2])

In [90]:
y = np.random.randint(1,10,5)
y

array([1, 9, 6, 6, 5])

In [91]:
np.concatenate((x,y))

array([8, 2, 6, 5, 2, 1, 9, 6, 6, 5])

In [93]:
# 2-d matrix

In [101]:
x = np.random.randint(1,10,(2,2))
x

array([[2, 4],
       [3, 9]])

In [102]:
y = np.random.randint(1,10,(2,2))
y

array([[3, 9],
       [4, 7]])

In [103]:
np.concatenate((x,y))

array([[2, 4],
       [3, 9],
       [3, 9],
       [4, 7]])

In [104]:
np.concatenate((x,y) , axis = 0)

array([[2, 4],
       [3, 9],
       [3, 9],
       [4, 7]])

In [106]:
x

array([[2, 4],
       [3, 9]])

In [107]:
y

array([[3, 9],
       [4, 7]])

In [108]:
np.concatenate((x,y) , axis = 1)

array([[2, 4, 3, 9],
       [3, 9, 4, 7]])

In [109]:
np.concatenate((x,y) , axis = None)

array([2, 4, 3, 9, 3, 9, 4, 7])

In [115]:
x = np.random.randint(1,10,(2,3))
x

array([[3, 1, 9],
       [2, 6, 5]])

In [118]:
y = np.random.randint(1,10,(3,3))
y

array([[5, 8, 7],
       [1, 6, 1],
       [2, 2, 7]])

In [119]:
np.concatenate((x,y) , axis = 0)

array([[3, 1, 9],
       [2, 6, 5],
       [5, 8, 7],
       [1, 6, 1],
       [2, 2, 7]])

In [120]:
# for loop

In [121]:
x = 5
for i in range(1,11):
    print(x*i)

5
10
15
20
25
30
35
40
45
50


In [122]:
# 1+2+3+4+5 = 15

In [130]:
x = 0
for i in range(1,6,1):
    x = x+i
x

15

In [124]:
10
9
8
7
6

6

In [125]:
for i in range(10,5,-1):
    print(i)

10
9
8
7
6


In [ ]:
for i in range(start , stop,step):
    print(i)

In [126]:
# while loop

In [129]:
i =  1       # start

while i <=10:  # stop
    print(i)
    i = i+1    # step (must)

1
2
3
4
5
6
7
8
9
10


In [131]:
# table

In [133]:
# sum of n natural num
# 1+2+3+4+5 = 15

In [134]:
i=1
while i<=10:
    print(5*i)
    i= i+1

5
10
15
20
25
30
35
40
45
50


In [135]:
i= 1
count = 0
while i<=5:
    count = count + i

    i= i+1
print(count)

15


In [136]:
# table 4 - 8

In [137]:
# for loop
# while loop

In [138]:
for i in range(4,9):
    for j in range(1, 11):
        print(i*j)
    print()

4
8
12
16
20
24
28
32
36
40

5
10
15
20
25
30
35
40
45
50

6
12
18
24
30
36
42
48
54
60

7
14
21
28
35
42
49
56
63
70

8
16
24
32
40
48
56
64
72
80



In [141]:
i= 4
while i<=8:
    j= 1
    while j <= 10:
        print(i*j , end = " ")
        j+= 1
    i +=1
    print()

4 8 12 16 20 24 28 32 36 40 
5 10 15 20 25 30 35 40 45 50 
6 12 18 24 30 36 42 48 54 60 
7 14 21 28 35 42 49 56 63 70 
8 16 24 32 40 48 56 64 72 80 


In [ ]:
1 2 3 4
1 2 3 4
1 2 3 4
1 2 3 4

In [142]:
1
12
123
1234

1234

In [143]:
for i in range(5):
    for j in range(1,5):
        print(j, end= " ")
    print()

1 2 3 4 
1 2 3 4 
1 2 3 4 
1 2 3 4 
1 2 3 4 


In [144]:
i = 1
while i<=4:
    j = 1
    while j<= 4:
        print(j, end=" ")
        j +=1
    print()
    i+=1

1 2 3 4 
1 2 3 4 
1 2 3 4 
1 2 3 4 


In [145]:
for i in range(1,5):
    for j in range(1,i+1):
        print(j, end= " ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 


In [146]:
i = 1
while i<=4:
    j = 1
    while j<= i:
        print(j, end=" ")
        j +=1
    print()
    i+=1

1 
1 2 
1 2 3 
1 2 3 4 


In [147]:
s = "anamika"

In [150]:
s = "anamiaaka"
count = 0
i =0
while i<len(s):
    if s[i] == "a":
        count+=1
    i+=1
print(count)

5


In [156]:
# 1d + 1d -> 1d

# 2d + 2d -> 2d

In [151]:
x = np.random.randint(1,10,(2,2))
x

array([[4, 4],
       [3, 4]])

In [152]:
y = np.random.randint(1,10,(2,2))
y

array([[5, 3],
       [3, 6]])

In [157]:
np.concatenate((x,y) , axis = 0)

array([[4, 4],
       [3, 4],
       [5, 3],
       [3, 6]])

In [158]:
np.concatenate((x,y) , axis = 1)

array([[4, 4, 5, 3],
       [3, 4, 3, 6]])

In [159]:
np.concatenate((x,y) , axis = None)

array([4, 4, 3, 4, 5, 3, 3, 6])

In [168]:
x = np.random.randint(1,10,(3,3))
x

array([[7, 1, 8],
       [9, 4, 4],
       [7, 4, 6]])

In [170]:
y = np.random.randint(1,10,(3,2))
y

array([[8, 1],
       [7, 7],
       [3, 8]])

In [172]:
np.concatenate((x,y) , axis = 1)

array([[7, 1, 8, 8, 1],
       [9, 4, 4, 7, 7],
       [7, 4, 6, 3, 8]])

In [173]:
# stacking

In [174]:
# 1d + 1d -> 2d

In [175]:
x = np.array([2,3,4,5])
y = np.array([1,2,3,4])

In [176]:
np.stack((x,y))

array([[2, 3, 4, 5],
       [1, 2, 3, 4]])

In [182]:
np.stack((x,y) , axis = 1)

array([[2, 1],
       [3, 2],
       [4, 3],
       [5, 4]])

In [183]:
# 2d +2d - 3d

In [186]:
x = np.random.randint(1,10,(2,2))
x

array([[5, 6],
       [7, 8]])

In [187]:
y = np.random.randint(1,10,(2,2))
y

array([[4, 7],
       [3, 1]])

In [188]:
np.stack((x,y))

array([[[5, 6],
        [7, 8]],

       [[4, 7],
        [3, 1]]])

In [191]:
np.stack((x,y) , axis = 1)

array([[[5, 6],
        [4, 7]],

       [[7, 8],
        [3, 1]]])

In [194]:
np.stack((x,y) , axis = 2)

array([[[5, 4],
        [6, 7]],

       [[7, 3],
        [8, 1]]])