# numpy

In [1]:
# numerical python library


In [2]:
# use for mathmtcl calc

In [3]:
# creatn of array
# matrix 
# sci cal
# diff equatn

In [4]:
# perform linear algebra
# linear regression
# neural netwrks

In [26]:
pip install numpy 

In [7]:
import numpy as np

In [8]:
np.__version__

'1.20.3'

In [12]:
# list vs numpy

# both are mutable

# list , we can not perform verctr operatn

In [13]:
l  = [1,2,3,4,5]

l+3

TypeError: can only concatenate list (not "int") to list

In [14]:
a = np.array([1,2,3,4])

In [15]:
a

array([1, 2, 3, 4])

In [16]:
a+6

array([ 7,  8,  9, 10])

In [17]:
# how to create numpy array

In [18]:
# array()
# arange()
# linspace()
# ones()
# zeroes()
# eye()
# identity()
# empty()

In [1]:
# np random module

# randint()
# rand()


In [1]:
#help(np.array)

#  array()

In [2]:
# 1 d array

In [23]:
# from list

l = [1,2,3,4,5]
type(l)

list

In [24]:
x = np.array(l)
x

array([1, 2, 3, 4, 5])

In [25]:
type(x)

numpy.ndarray

In [32]:
# dimension - dimension of array
# size - total num of elemnts in an array

# shape - m x n ---> m - rows , n - cols

In [31]:
# property

print("dimension --" , x.ndim)
print("dtype --" , x.dtype)
print("size--"   , x.size)
print("shape --" , x.shape)

dimension -- 1
dtype -- int32
size-- 5
shape -- (5,)


In [34]:
np.array((1,2,3))

array([1, 2, 3])

In [35]:
# create 2d array using nested list

In [36]:
l = [[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [38]:
x = np.array(l)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

dimension -- 2
size-- 6
shape -- (2, 3)


In [40]:
l = [[1,2,3],[4,5,6]]

x = np.array(l)

x

print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

dimension -- 2
size-- 6
shape -- (2, 3)


In [41]:
l = [[1,2,3,1],[2,4,5,6],[5,7,8,9]]

x = np.array(l)

x

print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

dimension -- 2
size-- 12
shape -- (3, 4)


In [47]:
l = [1,2,3,4,5]

x = np.array(l , dtype = float)


print(x)

print("dtype--" , x.dtype)
print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

[1. 2. 3. 4. 5.]
dtype-- float64
dimension -- 1
size-- 5
shape -- (5,)


In [49]:
l = [10,20.4,30,40.2,50.5]

x = np.array(l , dtype = int)


print(x)

print("dtype--" , x.dtype)
print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

[10 20 30 40 50]
dtype-- int32
dimension -- 1
size-- 5
shape -- (5,)


In [51]:
l = [10,-5,30,0,50]

x = np.array(l , dtype = bool)


print(x)

print("dtype--" , x.dtype)
print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

[ True  True  True False  True]
dtype-- bool
dimension -- 1
size-- 5
shape -- (5,)


# arange()

In [54]:
# help(np.arange)

In [55]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# linspace

In [61]:
x = np.linspace(1 ,10 , endpoint = False)
x

array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
       2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
       4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
       6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
       8.92, 9.1 , 9.28, 9.46, 9.64, 9.82])

In [71]:
x = np.linspace(1 ,10 , endpoint = True)   # include endpoint
x

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [67]:
x = np.linspace(1 ,10  ,20)
x

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [74]:
x = np.linspace(1 ,100  ,5)
x

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [77]:
x = np.ones(5 , dtype = int)
x

array([1, 1, 1, 1, 1])

In [79]:
x = np.ones((5 ,2) , dtype = int)
x

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [80]:
x = np.ones((3 ,4) , dtype = int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [81]:
# o-d array =  scaler
# 1-d array - vector (collectn of 0-d arrays)
# 2-d array - matrix (collectn of 1 d arrays)
# 3-d array - collectn of 2-d arrays

In [82]:
# (5,)   - 5 elemnt presnt 
# 

In [84]:
x = np.ones((2,3 ,4) , dtype = int)

print(x)

print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
dimension -- 3
size-- 24
shape -- (2, 3, 4)


In [85]:
x = np.ones((4 ,3 ,3) , dtype = int)

print(x)

print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
dimension -- 3
size-- 36
shape -- (4, 3, 3)


In [86]:
x = np.ones((2,2 ,3 ,3) , dtype = int)

print(x)

print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]
dimension -- 4
size-- 36
shape -- (2, 2, 3, 3)


In [87]:
x = np.ones((3,4 ,3 ,4) , dtype = int)

print(x)

print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

[[[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]]
dimension -- 4
size-- 144
shape -- (3, 4, 3, 4)


In [88]:
x = np.zeros((2 ,3 ,4) , dtype = int)

print(x)

print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
dimension -- 3
size-- 24
shape -- (2, 3, 4)


In [90]:
x = np.full((2 , 2 ,3) , 10 ,dtype = int)



print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

print(x)

dimension -- 3
size-- 12
shape -- (2, 2, 3)
[[[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]]


In [91]:
x+5

array([[[15, 15, 15],
        [15, 15, 15]],

       [[15, 15, 15],
        [15, 15, 15]]])

In [95]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
x = np.eye(5 , k = 1)
x

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [97]:
x = np.eye(5 , k = -1)
x

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [102]:
x = np.eye((3,2), k = -1)
x

TypeError: 'tuple' object cannot be interpreted as an integer

In [108]:
x = np.eye(3,2, k = -1)
x

array([[0., 0.],
       [1., 0.],
       [0., 1.]])

In [103]:
x = np.identity(5 , dtype = int)
x

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [109]:
# identity - always create sqre matrix - all diag value = 1

# eye - any shape  - all diag - 1

In [110]:
import numpy as np

In [111]:
# diag

In [116]:
x = np.array([10,60,30,40])

a = np.diag(x , k = 0)
a

array([[10,  0,  0,  0],
       [ 0, 60,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [118]:
# random

In [124]:
# random.randint  -- random int num

x = np.random.randint(5 ,10)
x

7

In [127]:
x = np.random.randint(1 ,10 , 4)
x

array([6, 8, 5, 1])

In [132]:
# create 2-d matrix using randint

In [134]:
x = np.random.randint(10 ,50 ,size =  (2 , 3 ,4))
x

array([[[37, 34, 39, 47],
        [29, 16, 40, 14],
        [48, 24, 15, 17]],

       [[32, 23, 47, 38],
        [35, 43, 18, 39],
        [15, 26, 30, 35]]])

In [137]:
# rand - genrate randm num bwn  0 -  1

In [138]:
x = np.random.rand(10)
x

array([0.42671132, 0.74453155, 0.60085028, 0.64087134, 0.37427151,
       0.93523991, 0.75739278, 0.20489784, 0.86686956, 0.43166695])

In [140]:
x = np.random.rand(5,3)
x

array([[0.1284397 , 0.45701175, 0.67859616],
       [0.53043698, 0.35239917, 0.69479702],
       [0.21221974, 0.85805829, 0.56443707],
       [0.36137113, 0.12217967, 0.47998019],
       [0.16317959, 0.7832348 , 0.95246738]])

# indexing , slicing

In [144]:
l = [10,20,30,40 , 50 ,60,70,80]

x = np.array(l)
x

array([10, 20, 30, 40, 50, 60, 70, 80])

In [145]:
x[3]

40

In [146]:
x[1:4]

array([20, 30, 40])

In [149]:
# advnce indxng

In [153]:
l = [10,20,30,40,50,60,70,80]
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [155]:
l[1::2]

[20, 40, 60, 80]

In [151]:
l[1:5]

[20, 30, 40, 50]

In [202]:
l = [10,20,30,40 , 50 ,60,70,80]

x = np.array(l)

x

array([10, 20, 30, 40, 50, 60, 70, 80])

In [203]:
x[[1,5,6,7]]

array([20, 60, 70, 80])

In [158]:
# access elemnts in 2d array

In [159]:
l = [[10,20,30],[40,50,60],[70,80,90]]

x = np.array(l)

x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [160]:
# 2-d array [rows][cols]

In [164]:
x[2,1]

80

In [166]:
x[-1][1]

80

In [167]:
l = [[10,20,30],[40,50,60],[70,80,90]]

x = np.array(l)

x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [168]:
x[0,1:]

array([20, 30])

In [174]:
x = np.arange(1,25).reshape(2 ,4,3)
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [176]:
# slicing

#           row                col
# array[start:stop:step , start:stop:step]

In [189]:
x = np.arange(1,101).reshape(10,10)
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [192]:
x[1,4]

15

In [182]:
x[3:9 , 1:4]

array([[32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84]])

In [180]:
x[7: , 7:]

array([[ 78,  79,  80],
       [ 88,  89,  90],
       [ 98,  99, 100]])

In [179]:
x[1:6 , 3:5]

array([[14, 15],
       [24, 25],
       [34, 35],
       [44, 45],
       [54, 55]])

In [183]:
# 3-d indexing slicing 

In [193]:
x = np.arange(1,37).reshape(3,3,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [194]:
# indexing
# array[axis][row][col]

# i , j , k

# i - axis
# j - row
# k - col

In [195]:
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [201]:
x[2,1,2]

31

In [200]:
x[0,2,3]

12

In [199]:
x[2,0,0]

25

In [198]:
x[1,2,2]

23

In [204]:
# slicing 3-d

In [205]:
# slicing

#          [axis]           [row]               [col]

# array[start:stop:step , start:stop:step , start:stop:step]


# i , j , k

# i - axis
# j - row
# k - col

In [206]:
x = np.arange(1,37).reshape(3,3,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [211]:
x[0:2 , 0::2 , 0::3]

array([[[ 1,  4],
        [ 9, 12]],

       [[13, 16],
        [21, 24]]])

In [209]:
x[0: ,1: ,2: ]

array([[[ 7,  8],
        [11, 12]],

       [[19, 20],
        [23, 24]],

       [[31, 32],
        [35, 36]]])

In [208]:
x[1 , 1: , 0:3]

array([[17, 18, 19],
       [21, 22, 23]])

In [207]:
x[0 , 2 , 1:]

array([10, 11, 12])

In [1]:
import numpy as np

In [4]:
l = [1,2,3,1,1,2,2,3,3,2,4,5,4]

l1 = []

for i in l:
    if i not in l1:
        l1.append(i)
l1

[1, 2, 3, 4, 5]

In [5]:
l = [1,2,3,1,1,2,2,3,3,2,4,5,4]

for i in l:
    if l.count(i)>1:
        l.remove(i)
l

[1, 2, 2, 3, 2, 5, 4]

In [6]:
# indexing - 1d , 2d , 3d
# slciing  - 1d , 2d , 3d 

In [7]:
# advance indecing

In [8]:
# 1d

In [10]:
l = [10,20,30,40,50,60,70]

x = np.array(l)
x

array([10, 20, 30, 40, 50, 60, 70])

In [14]:
x[[1,4,5]]

array([20, 50, 60])

In [15]:
x = np.arange(1,101).reshape(10,10)
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [17]:
x[4:7:2 , 0::4]

array([[41, 45, 49],
       [61, 65, 69]])

In [24]:
x = np.arange(1,17).reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
x[[0,1,2,3,3,3,3],[0,0,0,0,1,2,3]]

array([ 1,  5,  9, 13, 14, 15, 16])

In [23]:
# 5 , 11 , 4

x[[1,2,0],[0,2,3]]

array([ 5, 11,  4])

In [22]:
x[[2 , 3] , [0,1]]

array([ 9, 14])

In [19]:
x[[0,1,2,3],[0,1,2,3]]

array([ 1,  6, 11, 16])

In [29]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [30]:
y = np.array([[5,2],[3,1]])
y

array([[5, 2],
       [3, 1]])

In [31]:
x*y

array([[5, 4],
       [9, 4]])

In [38]:
a = np.ones((2,2) , dtype= int)
a

array([[1, 1],
       [1, 1]])

In [40]:
# 3d - advance indxng
# x[[axis] ,[row] , [col]]

In [42]:
x = np.arange(1,37).reshape(3,3,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [46]:
x[[1 , 0 , 1] , [1 , 2 , 2] , [0 ,2 , 3]]

array([17, 11, 24])

In [43]:
x[[0,1] , [2 , 1] , [1 ,2]]

array([10, 19])

In [47]:
# airthmetic opr
import numpy as np

In [48]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [49]:
x+6

array([ 7,  8,  9, 10, 11, 12])

In [50]:
x-2

array([-1,  0,  1,  2,  3,  4])

In [51]:
x*3

array([ 3,  6,  9, 12, 15, 18])

In [52]:
x/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [53]:
x

array([1, 2, 3, 4, 5, 6])

In [54]:
np.add(x ,2)

array([3, 4, 5, 6, 7, 8])

In [61]:
x = np.array([10,12,23,14,45,26])
y = np.array([1,2,3,4,5 , 6])


In [62]:
x+y

array([11, 14, 26, 18, 50, 32])

In [63]:
x = np.arange(1,13).reshape(3,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
x+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
x-2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [66]:
x = np.array([31,20,13,40,58,62])
x

array([31, 20, 13, 40, 58, 62])

In [67]:
sum(x)

224

In [68]:
max(x)

62

In [69]:
min(x)

13

In [72]:
np.average(x)

37.333333333333336

In [74]:
np.std(x)

18.144481867009105

In [75]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
np.sum(x , axis = 0)   # for col 

array([12, 15, 18])

In [84]:
np.sum(x , axis = 0) [2] 

18

In [81]:
np.sum(x , axis = 1)   # for rows

array([ 6, 15, 24])

In [83]:
np.sum(x , axis = 1)[1] 

15

In [85]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
np.max(x , axis = 0)

array([7, 8, 9])

In [92]:
np.max(x , axis = 1)

array([3, 6, 9])

In [93]:
# argmin  - return index value of min elemnt
# argmax  - return index of max elemnt 

In [94]:
x = np.array([12,24,43,12,10,5,8])
x

array([12, 24, 43, 12, 10,  5,  8])

In [96]:
np.argmax(x)

2

In [97]:
np.argmin(x)

5

In [98]:
np.sqrt(x)

array([3.46410162, 4.89897949, 6.55743852, 3.46410162, 3.16227766,
       2.23606798, 2.82842712])

In [99]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(1,10).reshape(3,3)

In [100]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
x+y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [103]:
x-y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [107]:
x*y             # cross product

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [106]:
x@y             # dot product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [1]:
import numpy as np

In [2]:
l = [[1,2],[3,4]]
x = np.array(l)
x

array([[1, 2],
       [3, 4]])

In [3]:
l = [[1,2],[3,4]]
y= np.array(l)
y

array([[1, 2],
       [3, 4]])

In [4]:
# cross prod

In [5]:
x*y

array([[ 1,  4],
       [ 9, 16]])

In [10]:
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[1 2]
 [3 4]]


In [6]:
x@y

array([[ 7, 10],
       [15, 22]])

In [7]:
np.dot(x,y)

array([[ 7, 10],
       [15, 22]])

In [11]:
# possibilties ?

# m1 x n1    m2 x n2             --->  result   ? x ?     

In [12]:
# 3x2      2x2        --> 

# 2x3       2x2       --> 

In [15]:
x = np.arange(1,7).reshape(3,2)

y = np.arange(1,5).reshape(2,2)


In [16]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
y

array([[1, 2],
       [3, 4]])

In [19]:
x@y

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [20]:
x = np.arange(1,7).reshape(2,3)

y = np.arange(1,5).reshape(2,2)

In [21]:
x@y

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [22]:
# matrix dot product 


# r1 x c1      r2  x  c2


# if c1 = r2   then only we can perform dot product


# o/p  ? x ?   ----->      r1 x c2 

In [23]:
x = np.arange(1,13).reshape(4,3)

y = np.arange(1,13).reshape(3 , 4)

In [24]:
x@y

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272]])

In [29]:
x = np.arange(1,9).reshape(4,2)

y = np.arange(1,9).reshape(2,4)

In [31]:
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
x@y

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68],
       [47, 62, 77, 92]])

In [1]:
import numpy as np

In [2]:
x = np.arange(1,5).reshape(2,2)

y = np.arange(1,5).reshape(2,2)


In [3]:
x

array([[1, 2],
       [3, 4]])

In [4]:
y

array([[1, 2],
       [3, 4]])

In [5]:
l = np.ones((2,2) , dtype = int)
l

array([[1, 1],
       [1, 1]])

In [6]:
for i in x:
    for j in y:
        l[i][j] = x[i][j] * y[j][i]
l

IndexError: index 2 is out of bounds for axis 0 with size 2

In [10]:
z = np.ones((2,2) , dtype = int)
z

array([[1, 1],
       [1, 1]])

In [11]:
x = np.arange(1,5).reshape(2,2)

y = np.arange(1,5).reshape(2,2)

x

array([[1, 2],
       [3, 4]])

In [12]:
y

array([[1, 2],
       [3, 4]])

In [13]:

for i in range(len(x)):
    for j in range(len(y)):
        for k in range(len(y)):
            z[i][j] = x[i][k] * y[k][j]
z


array([[ 6,  8],
       [12, 16]])

# how to iterate elemnts of nd array

In [49]:
# use python loop
# use nditer()
# ndenumerate()

In [50]:
x = np.arange(10,61,10)
x

array([10, 20, 30, 40, 50, 60])

In [51]:
for i in x:
    print(i)

10
20
30
40
50
60


In [52]:
# 2 - d

In [62]:
x = np.array([[10,20,30],[40,50,60],[70,80,90]])
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [63]:
for i in np.nditer(x):
    print(i)

10
20
30
40
50
60
70
80
90


In [56]:
for i in x:
    for j in i:
        print(j , end =" ")
    print()

10 20 30 
40 50 60 
70 80 90 


In [64]:
x = np.array([[[10,20],[30,40]]  , [[50,60] , [70,80]]])
x

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [61]:
for i in x:
    for j in i:
        for k in j:
            print(k , end =" ")
        print()

10 20 
30 40 
50 60 
70 80 


In [65]:
for i in np.nditer(x):
    print(i)

10
20
30
40
50
60
70
80


In [66]:
x = np.arange(10,61,10)
x

array([10, 20, 30, 40, 50, 60])

In [69]:
for i  , j in np.ndenumerate(x):
    print(i , "-elemnt present at index value =" , j)

(0,) -elemnt present at index value = 10
(1,) -elemnt present at index value = 20
(2,) -elemnt present at index value = 30
(3,) -elemnt present at index value = 40
(4,) -elemnt present at index value = 50
(5,) -elemnt present at index value = 60


In [70]:
x = np.array([[10,20,30],[40,50,60],[70,80,90]])
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [71]:
for i  , j in np.ndenumerate(x):
    print(i , "-elemnt present at index value =" , j)

(0, 0) -elemnt present at index value = 10
(0, 1) -elemnt present at index value = 20
(0, 2) -elemnt present at index value = 30
(1, 0) -elemnt present at index value = 40
(1, 1) -elemnt present at index value = 50
(1, 2) -elemnt present at index value = 60
(2, 0) -elemnt present at index value = 70
(2, 1) -elemnt present at index value = 80
(2, 2) -elemnt present at index value = 90


In [72]:
x = np.array([[[10,20],[30,40]]  , [[50,60] , [70,80]]])
x

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [73]:
for i  , j in np.ndenumerate(x):
    print(i , "-elemnt present at index value =" , j)

(0, 0, 0) -elemnt present at index value = 10
(0, 0, 1) -elemnt present at index value = 20
(0, 1, 0) -elemnt present at index value = 30
(0, 1, 1) -elemnt present at index value = 40
(1, 0, 0) -elemnt present at index value = 50
(1, 0, 1) -elemnt present at index value = 60
(1, 1, 0) -elemnt present at index value = 70
(1, 1, 1) -elemnt present at index value = 80


In [82]:
x = np.array([[10,20,30],[40,50,60],[70,80,90]])
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# joining multiple array into single array

In [205]:
# concatenate()

# stack()

# vstack()

# hstack()

# dstack()

In [92]:
import numpy as np

# concatenate

In [94]:
# axis = 0  -->  vertical concatenatn
# axis = 1  -->  horizontal concat
# axis = None -->  frst array will be flatten (converted into 1-d array) and thn conct will happn

In [95]:
# 1-d array

In [101]:
a = np.arange(4)
b = np.arange(5)
c = np.arange(3)

np.concatenate((a,b,c))

array([0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2])

In [106]:
a = np.arange(4)
b = np.arange(5)
c = np.arange(3)

x = np.concatenate((a,b,c))

print(x)

# axis = 0

y = np.concatenate((a,b,c) , axis = 0)
print(y)


z = np.concatenate((a,b,c) , axis = None)
print(z)

[0 1 2 3 0 1 2 3 4 0 1 2]
[0 1 2 3 0 1 2 3 4 0 1 2]
[0 1 2 3 0 1 2 3 4 0 1 2]


In [107]:
# 2 - d array

In [114]:
# by default axis = 0

In [119]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# by default  vertcl

x = np.concatenate((a , b))
print("vertical \n",x)


# axis = 0

y = np.concatenate((a , b) , axis = 0)
print("verticl \n" , y)


# axis = 1
z = np.concatenate((a , b) , axis = 1)
print("horizntal \n" , z)

# axis = None
l = np.concatenate((a , b) , axis = None)
print("1-d array concat \n" , l)

vertical 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
verticl 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizntal 
 [[1 2 5 6]
 [3 4 7 8]]
1-d array concat 
 [1 2 3 4 5 6 7 8]


In [122]:
a = np.arange(6).reshape(2,3)

b = np.arange(1 ,16).reshape(5,3)

# axis = None
l = np.concatenate((a , b) , axis = None)
print("1-d array concat \n" , l)

1-d array concat 
 [ 0  1  2  3  4  5  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [123]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [124]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [127]:
a = np.arange(1 , 7).reshape(2,3)

b = np.arange(1 ,16).reshape(5,3)


# axis = 0

y = np.concatenate((a , b) , axis = 0)
print("verticl \n" , y)



verticl 
 [[ 1  2  3]
 [ 4  5  6]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [129]:
a = np.arange(6).reshape(2,3)

b = np.arange(1 ,16).reshape(5,3)


# axis = 1
z = np.concatenate((a , b) , axis = 1)
print("horizntal \n" , z)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 5

In [130]:
# out

In [140]:
a = np.arange(1 , 7).reshape(2,3)

b = np.arange(1 ,16).reshape(5,3)


# axis = 0

arun = np.empty((7,3))

np.concatenate((a , b) , axis = 0 , out = arun )


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [141]:
arun

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [151]:
a = np.arange(1,7).reshape(3,2)

b = np.arange(1 ,16).reshape(3,5)


a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [153]:
np.concatenate((a , b) , axis = 1)

array([[ 1,  2,  1,  2,  3,  4,  5],
       [ 3,  4,  6,  7,  8,  9, 10],
       [ 5,  6, 11, 12, 13, 14, 15]])

In [154]:
X=np.arange(1,5).reshape(2,2)
Y=np.arange(1,5).reshape(2,2)

Z=np.zeros((2,2), int)

# iterate through rows of X

for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
            Z[i][j] += X[i][k] * Y[k][j]
Z


array([[ 7, 10],
       [15, 22]])

In [155]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]


# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [162]:
X =np.arange(1,25).reshape(6,4)
Y =np.arange(1,9).reshape(4,2)

Z=np.zeros((X.shape[0],Y.shape[1]), int)

# iterate through rows of X

for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
            Z[i][j] += X[i][k] * Y[k][j]
Z


array([[ 50,  60],
       [114, 140],
       [178, 220],
       [242, 300],
       [306, 380],
       [370, 460]])

In [160]:
x = np.arange(1,13).reshape(3,4)
x.shape[0]

3

In [189]:
x = np.arange(1,37).reshape(6,6)

x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [190]:
s = 0

for i  , j  in np.ndenumerate(x):
    if i[0] == i[1]:
        s = s + j
s

111

In [193]:
x = np.arange(1,19).reshape(2 , 3,3)

x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [197]:
s = 0
for i  , j  in np.ndenumerate(x):
    if i[1] == i[2]:
        s = s + j
s

57

In [198]:
x = np.arange(1,19).reshape(2 , 3,3)
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [204]:
s1 = 0
s2 = 0

l = []

for i  , j  in np.ndenumerate(x):
    if i[0] ==  i[1] == i[2]:
        s1 = s1+j
        
        
    elif i[1] == i[1] == i[2]:
        s2 = s2+j
        
l.append(s1)
l.append(s2)
l

[15, 42]

In [206]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a

array([[1, 2],
       [3, 4]])

In [207]:
b

array([[5, 6],
       [7, 8]])

In [208]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [209]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [215]:
np.stack((a,b) , axis = 0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [216]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])


In [217]:
a

array([[1, 2],
       [3, 4]])

In [218]:
b

array([[5, 6],
       [7, 8]])

In [219]:
np.stack((a,b) , axis = 0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [220]:
np.stack((a,b) , axis = 1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [221]:
np.stack((a,b) , axis = 2)

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [225]:
a = np.empty((4,3))
a

array([[1.20353379e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.10343781e-312, 2.65128566e-032],
       [1.59990574e+160, 7.26117134e-043, 2.44599743e-056],
       [5.88080619e-062, 4.75085788e+174, 3.98356954e-062]])

In [1]:
l1 = [7, 4, 5, 1]
l2 = [2, 3, 6]



In [2]:
# Write a Python program to find numbers between 300 and 800 (both included) where  
# each digit of a number is an even number.
# The numbers obtained should be printed in a comma-separated sequence.

In [6]:
# 402 , 424 , 484 , 444 , 422 ,648 , 626

In [5]:
for i in range(300 , 801):
    if i%2 ==0:
        print(i , end =" ")

300 302 304 306 308 310 312 314 316 318 320 322 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466 468 470 472 474 476 478 480 482 484 486 488 490 492 494 496 498 500 502 504 506 508 510 512 514 516 518 520 522 524 526 528 530 532 534 536 538 540 542 544 546 548 550 552 554 556 558 560 562 564 566 568 570 572 574 576 578 580 582 584 586 588 590 592 594 596 598 600 602 604 606 608 610 612 614 616 618 620 622 624 626 628 630 632 634 636 638 640 642 644 646 648 650 652 654 656 658 660 662 664 666 668 670 672 674 676 678 680 682 684 686 688 690 692 694 696 698 700 702 704 706 708 710 712 714 716 718 720 722 724 726 728 730 732 734 736 738 740 742 744 746 748 750 752 754 756 758 760 762 764 766 768 770 772 774 776 778 780 782 784 786 788 790 792 794 796 798 

In [17]:
for i in range(301 , 800):
    x = str(i)
    
    if int(x[0])%2==0 and int(x[1])%2==0 and int(x[2])%2==0:
        print(i)

400
402
404
406
408
420
422
424
426
428
440
442
444
446
448
460
462
464
466
468
480
482
484
486
488
600
602
604
606
608
620
622
624
626
628
640
642
644
646
648
660
662
664
666
668
680
682
684
686
688


In [12]:
i = 404

d = str(i)
d

'404'

In [15]:
int(d[0]) %2

0

In [20]:
l = ["s", "t", "r", "i", "n", "g", "w"]

s = "string"

for i in l:
    if i not in s:
        print(i)

w


In [21]:
l1 = [7, 4, 5, 1]

l2 = [2, 3, 6]

l = l1+l2

In [22]:
l

[7, 4, 5, 1, 2, 3, 6]

In [23]:
l.sort()

In [24]:
l

[1, 2, 3, 4, 5, 6, 7]

In [25]:
l = [1, 2, 3, 4, 5, 6, 7]


In [30]:
l = [1, 2, 3, 4,5, 6, 7]

x = min(l)

y = max(l)

l3 = list(range(x,y+1))

l3

if l == l3:
    print("cons")
else:
    print("not cons")

cons


In [31]:
list(range(1,5))

[1, 2, 3, 4]

In [32]:
l2 = []

for i in range(1,6):
    l2.append(i)
l2


[1, 2, 3, 4, 5]

In [33]:
# list comp
# dictionary
# set , tuple

# function
# file hand
# reg exp
# modules
# oops

In [36]:
# database
# numpy
# pandas
# matplot


# tableau

In [37]:
# ml