In [1]:
# array

In [2]:
import numpy as np

In [3]:
l = [2,3,4,5]
l

[2, 3, 4, 5]

In [4]:
l*3

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

In [5]:
x = np.array(l)
x

array([2, 3, 4, 5])

In [6]:
x*3

array([ 6,  9, 12, 15])

In [189]:
# array()
# arange()
# linspace()
# ones()
# zeroes()
# eye()
# identity()

In [8]:
# array()

In [9]:
l = [2,3,4,5,6]
l

[2, 3, 4, 5, 6]

In [10]:
x = np.array(l)
x

array([2, 3, 4, 5, 6])

In [13]:
# shape of an array
x.shape

(5,)

In [16]:
# size of array - (total no of elemnts in array)
x.size

5

In [17]:
# dimension of array
x.ndim

1

In [18]:
type(x)

numpy.ndarray

In [19]:
# create 2 d matrix

In [20]:
l = [[1,2,3],[4,5,6],[7,8,9]]

x = np.array(l)

x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

dimension -- 2
size-- 9
shape -- (3, 3)


In [23]:
# shape -> rows x columns

In [25]:
l = [[1,2,3],[4,5,6]]

x = np.array(l)

x

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

dimension -- 2
size-- 6
shape -- (2, 3)


In [27]:
l = [[1,2],[4,6],[7,8]]

x = np.array(l)

x

array([[1, 2],
       [4, 6],
       [7, 8]])

In [28]:
print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

dimension -- 2
size-- 6
shape -- (3, 2)


In [29]:
l = [[[1,2,3],[4,5,6]] , [[8,7,6],[5,4,9]]]

x = np.array(l)

x

array([[[1, 2, 3],
        [4, 5, 6]],

       [[8, 7, 6],
        [5, 4, 9]]])

In [30]:
print("dimension --" , x.ndim)
print("size--"   , x.size)
print("shape --" , x.shape)

dimension -- 3
size-- 12
shape -- (2, 2, 3)


In [31]:
# arange()

In [32]:
x = np.arange(1,9)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
x = np.arange(1,9,2)
x

array([1, 3, 5, 7])

In [37]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
# linspace()
# ones()
# zeroes()
# eye()
# identity()


In [44]:
# 50 equal parts

x = np.linspace(1,5)
x

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [54]:
x = np.linspace(0,100,10)
x

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [55]:
# ones()

In [60]:
x = np.ones((3,4) , dtype = int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [61]:
x = np.zeros((3,4) , dtype = int)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [86]:
# eye() - any shape
# identity() - square matrix

In [82]:
x = np.eye(3,4, dtype = int)
x

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [84]:
x = np.identity(3, dtype = int)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [98]:
# random module

# rand() - between (0 - 1)
# randint()

In [99]:
x = np.random.rand(4)
x

array([0.3816576 , 0.30668692, 0.85147808, 0.04181106])

In [100]:
x = np.random.rand(3,4)
x

array([[0.85527507, 0.44397457, 0.47910218, 0.51198143],
       [0.16881277, 0.41270331, 0.95010964, 0.71848247],
       [0.79821839, 0.59018615, 0.02505733, 0.29558993]])

In [106]:
x = np.random.randint(10,17)
x

10

In [108]:
x = np.random.randint(10,17,5)
x

array([11, 15, 10, 12, 15])

In [112]:
x = np.random.randint(10,80,(4,3))
x

array([[78, 63, 50],
       [18, 79, 18],
       [61, 63, 34],
       [64, 73, 37]])

In [115]:
# array()
# arange()
# linspace()
# ones()
# zeroes()
# eye()
# identity()
# empty()

# np random module
# randint()
# rand()


In [126]:
np.random.normal(5,4,(3,4)) 

array([[12.86029542,  8.13325959,  3.92659727,  8.31890177],
       [ 3.16332128, -5.47373184,  3.91866347,  5.67270986],
       [ 5.16653493,  7.06544947,  1.60676151, 11.10507619]])

In [127]:
# manipulation

In [128]:
# sum , max , min , addition
# indexing , slicing
# advance indexing

In [129]:
l = [3,4,5]
l

[3, 4, 5]

In [130]:
l+3

TypeError: can only concatenate list (not "int") to list

In [131]:
x = np.array(l)
x

array([3, 4, 5])

In [132]:
x+3

array([6, 7, 8])

In [133]:
x

array([3, 4, 5])

In [134]:
# how to create array

In [174]:
# array()
# arange()
# linspace()
# ones()
# zeroes()
# eye()
# identity()

In [136]:
x = np.array([3,4,5,6,7,8])
x

array([3, 4, 5, 6, 7, 8])

In [137]:
x.shape

(6,)

In [138]:
x.ndim

1

In [139]:
x = np.array([[3,4,5],[6,7,8]])
x

array([[3, 4, 5],
       [6, 7, 8]])

In [140]:
x.ndim

2

In [141]:
x.shape

(2, 3)

In [142]:
# rows x columns

In [144]:
x = np.arange(1,9,2)
x

array([1, 3, 5, 7])

In [149]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [150]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [167]:
# by default 50 equal partition

x = np.linspace(10,60,8)
x

array([10.        , 17.14285714, 24.28571429, 31.42857143, 38.57142857,
       45.71428571, 52.85714286, 60.        ])

In [172]:
x = np.ones((3,4) , dtype = int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [173]:
x = np.zeros((3,4) , dtype = int)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [178]:
# intervw qns

In [183]:
x = np.eye(3,4, dtype = int)
x

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [186]:
# only square matrix

x = np.identity(3, dtype = int)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [187]:
# random

In [188]:
import numpy as np

In [198]:
# 2d + 2d +2d --> 3 d matrix

In [190]:
# indexing 
# slicing

In [191]:
x = np.array([1,2,3,4,5,6,7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [192]:
x[0]

1

In [193]:
x[2]

3

In [194]:
x[-1]

8

In [195]:
# slicing

In [196]:
x[2:7]

array([3, 4, 5, 6, 7])

In [197]:
# slicing 

In [199]:
#          row              column
# s[start:stop:step , start :stop :step]

In [201]:
x = np.arange(0,100).reshape(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
10 12 14
30 22 34
50 52 54

In [206]:
x[1:6:2, 0:5:2]

array([[10, 12, 14],
       [30, 32, 34],
       [50, 52, 54]])

In [205]:
x[2:6,2:6]

array([[22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55]])

In [203]:
x[0:5,::]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [204]:
x[:,4:8]

array([[ 4,  5,  6,  7],
       [14, 15, 16, 17],
       [24, 25, 26, 27],
       [34, 35, 36, 37],
       [44, 45, 46, 47],
       [54, 55, 56, 57],
       [64, 65, 66, 67],
       [74, 75, 76, 77],
       [84, 85, 86, 87],
       [94, 95, 96, 97]])

In [218]:
# advance indexing
# in array we can pass multiple indexing

In [208]:
x = np.array([1,2,3,4,5,6,7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [211]:
x[0:5:2]

array([1, 3, 5])

In [213]:
x[[0,2,3,6,7]]

array([1, 3, 4, 7, 8])

In [215]:
l = [1,2,3,4,5,6]

In [219]:
# 2-d array

In [220]:
x = np.arange(1,17).reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [224]:
x[[0,1,1],[1,0,2]]

array([2, 5, 7])

In [225]:
# 1 5 9 13 14 15 16

In [231]:
x[[0,1,2,3,3,3,3],[0,0,0,0,1,2,3]]

array([ 1,  5,  9, 13, 14, 15, 16])

In [232]:
# add , sub ,mul , div

In [233]:
x = np.array([1,2,3,4,5,6,7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [234]:
x+2

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [235]:
x-2

array([-1,  0,  1,  2,  3,  4,  5,  6])

In [236]:
x*3

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [237]:
x/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [238]:
x//2

array([0, 1, 1, 2, 2, 3, 3, 4], dtype=int32)

In [239]:
x%2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [240]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [241]:
x+2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [242]:
x*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [243]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [244]:
x**.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [245]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [246]:
np.add(x,3)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [247]:
x+3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [248]:
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [249]:
np.log(x)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [250]:
np.log10(x)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [255]:
import numpy as np

In [258]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [259]:
x.sum()

45

In [260]:
x.max()

9

In [261]:
x.sum()

45

In [266]:
x = np.random.randint(3,40,(3,4))
x

array([[25, 36, 11, 14],
       [16, 32,  9, 12],
       [18, 30,  6, 15]])

In [267]:
x

array([[25, 36, 11, 14],
       [16, 32,  9, 12],
       [18, 30,  6, 15]])

In [270]:
x.sum(axis = 1)   # for rows

array([86, 69, 69])

In [272]:
x.sum(axis = 0)  # for columns

array([59, 98, 26, 41])

In [274]:
x

array([[25, 36, 11, 14],
       [16, 32,  9, 12],
       [18, 30,  6, 15]])

In [273]:
x.max()

36

In [275]:
x.max(axis = 1)

array([36, 32, 30])

In [276]:
x.max(axis = 0)

array([25, 36, 11, 15])

In [278]:
x

array([[25, 36, 11, 14],
       [16, 32,  9, 12],
       [18, 30,  6, 15]])

In [277]:
x.min()

6

In [279]:
x.min(axis = 1)

array([11,  9,  6])

In [280]:
x.min(axis = 0)

array([16, 30,  6, 12])

In [282]:
np.max(x , axis = 0)

array([25, 36, 11, 15])

In [283]:
x

array([[25, 36, 11, 14],
       [16, 32,  9, 12],
       [18, 30,  6, 15]])

In [284]:
x+2

array([[27, 38, 13, 16],
       [18, 34, 11, 14],
       [20, 32,  8, 17]])

In [285]:
x*3

array([[ 75, 108,  33,  42],
       [ 48,  96,  27,  36],
       [ 54,  90,  18,  45]])

In [286]:
x/3

array([[ 8.33333333, 12.        ,  3.66666667,  4.66666667],
       [ 5.33333333, 10.66666667,  3.        ,  4.        ],
       [ 6.        , 10.        ,  2.        ,  5.        ]])

In [287]:
x

array([[25, 36, 11, 14],
       [16, 32,  9, 12],
       [18, 30,  6, 15]])

In [288]:
# how to iterate over array

In [289]:
# python loop
# nditer
# ndenumerate

In [290]:
x = np.array([2,3,4,5,6,7])
x

array([2, 3, 4, 5, 6, 7])

In [291]:
for i in x:
    print(i)

2
3
4
5
6
7


In [293]:
x= np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [298]:
x[1][0]

4

In [296]:
x[0][1]

2

In [297]:
x[1][2]

6

In [299]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [301]:
for i in x:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [302]:
x= np.arange(1,19).reshape(2,3,3)
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [305]:
for i in x:
    for j in i:
        for k in j:
            print(k)
    

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [307]:
# nditer

In [308]:
x= np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [310]:
for i in np.nditer(x):
    print(i)

1
2
3
4
5
6
7
8
9


In [311]:
x= np.arange(1,19).reshape(2,3,3)
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [312]:
for i in np.nditer(x):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [313]:
# ndenumerate

In [314]:
l = ["arun",20,30,40,"ram",50]
l

['arun', 20, 30, 40, 'ram', 50]

In [317]:
for i in range(len(l)):
    print(i , l[i])

0 arun
1 20
2 30
3 40
4 ram
5 50


In [318]:
l = ["arun",20,30,40,"ram",50]
l

['arun', 20, 30, 40, 'ram', 50]

In [321]:
for i , j in enumerate(l):
    print(i ,"--", j)

0 -- arun
1 -- 20
2 -- 30
3 -- 40
4 -- ram
5 -- 50


In [322]:
x = np.array([2,3,4,5,6,7])
x

array([2, 3, 4, 5, 6, 7])

In [324]:
for i in np.ndenumerate(x):
    print(i)

((0,), 2)
((1,), 3)
((2,), 4)
((3,), 5)
((4,), 6)
((5,), 7)


In [325]:
x= np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [326]:
for i in np.ndenumerate(x):
    print(i)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((1, 0), 4)
((1, 1), 5)
((1, 2), 6)
((2, 0), 7)
((2, 1), 8)
((2, 2), 9)


In [327]:
x= np.arange(1,19).reshape(2,3,3)
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [328]:
for i in np.ndenumerate(x):
    print(i)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 6)
((0, 2, 0), 7)
((0, 2, 1), 8)
((0, 2, 2), 9)
((1, 0, 0), 10)
((1, 0, 1), 11)
((1, 0, 2), 12)
((1, 1, 0), 13)
((1, 1, 1), 14)
((1, 1, 2), 15)
((1, 2, 0), 16)
((1, 2, 1), 17)
((1, 2, 2), 18)


In [350]:
# 10 batch - course 
# basic - zero
# numpy , pandas 

In [336]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [345]:
for i  in range(len(x)):
    for j in range(len(x[i])):
        print(i,j, "----",x[i][j])

0 0 ---- 1
0 1 ---- 2
0 2 ---- 3
1 0 ---- 4
1 1 ---- 5
1 2 ---- 6
2 0 ---- 7
2 1 ---- 8
2 2 ---- 9


In [353]:
x[0][1]

2

In [356]:
# concatenation
# stacking

In [357]:
# 2 matrix - concat

In [361]:
# 1-d array

In [362]:
# 1d + 1d => 1d

In [358]:
x = np.array([2,3,4,5,6])
y = np.array([1,2,3,4,5])

In [363]:
x

array([2, 3, 4, 5, 6])

In [364]:
y

array([1, 2, 3, 4, 5])

In [365]:
np.concatenate((x,y))

array([2, 3, 4, 5, 6, 1, 2, 3, 4, 5])

In [367]:
# 2d array

# 2d + 2d = 2d array

In [368]:
x = np.random.randint(1,30,(3,3))
x

array([[19, 10, 24],
       [ 6, 17,  8],
       [27, 25,  5]])

In [369]:
y = np.random.randint(1,30,(3,3))
y

array([[ 5,  3,  1],
       [ 5, 28, 14],
       [19, 18, 21]])

In [370]:
np.concatenate((x,y))

array([[19, 10, 24],
       [ 6, 17,  8],
       [27, 25,  5],
       [ 5,  3,  1],
       [ 5, 28, 14],
       [19, 18, 21]])

In [371]:
np.concatenate((x,y) , axis = 0)

array([[19, 10, 24],
       [ 6, 17,  8],
       [27, 25,  5],
       [ 5,  3,  1],
       [ 5, 28, 14],
       [19, 18, 21]])

In [372]:
np.concatenate((x,y) , axis = 1)

array([[19, 10, 24,  5,  3,  1],
       [ 6, 17,  8,  5, 28, 14],
       [27, 25,  5, 19, 18, 21]])

In [373]:
np.concatenate((x,y) , axis = None)

array([19, 10, 24,  6, 17,  8, 27, 25,  5,  5,  3,  1,  5, 28, 14, 19, 18,
       21])

In [374]:
# axis = None - frst all matrix will converted into 1d and thn concatenation will perform

In [377]:
x = np.random.randint(1,30,(3,3))
x

array([[11, 11, 10],
       [26, 15,  4],
       [14,  5, 20]])

In [382]:
y = np.random.randint(1,30,(3,4))
y

array([[19, 18, 26, 15],
       [15, 16, 28, 16],
       [ 4, 16, 13, 26]])

In [384]:
np.concatenate((x,y) , axis = 1)

array([[11, 11, 10, 19, 18, 26, 15],
       [26, 15,  4, 15, 16, 28, 16],
       [14,  5, 20,  4, 16, 13, 26]])

In [386]:
# stack

In [387]:
# 1-d

# 1d + 1d -> 2d

In [388]:
x =  np.array([3,4,5,6])
x

array([3, 4, 5, 6])

In [389]:
y = np.array([1,2,3,4])
y

array([1, 2, 3, 4])

In [393]:
np.stack((x,y) , axis = 0)

array([[3, 4, 5, 6],
       [1, 2, 3, 4]])

In [395]:
a = np.stack((x,y) , axis = 1)

In [396]:
a

array([[3, 1],
       [4, 2],
       [5, 3],
       [6, 4]])

In [397]:
a.ndim

2

In [401]:
# 2d + 2d -> 3d

In [398]:
x = np.random.randint(1,30,(3,3))
x

array([[21, 15, 21],
       [29, 21, 21],
       [23, 15,  6]])

In [400]:
y = np.random.randint(1,30,(3,3))
y

array([[11,  3, 10],
       [ 7, 25, 17],
       [18, 18, 27]])

In [404]:
np.stack((x,y) , axis = 0)

array([[[21, 15, 21],
        [29, 21, 21],
        [23, 15,  6]],

       [[11,  3, 10],
        [ 7, 25, 17],
        [18, 18, 27]]])

In [403]:
np.stack((x,y) , axis = 1)

array([[[21, 15, 21],
        [11,  3, 10]],

       [[29, 21, 21],
        [ 7, 25, 17]],

       [[23, 15,  6],
        [18, 18, 27]]])

In [405]:
np.stack((x,y) , axis = 2)

array([[[21, 11],
        [15,  3],
        [21, 10]],

       [[29,  7],
        [21, 25],
        [21, 17]],

       [[23, 18],
        [15, 18],
        [ 6, 27]]])

In [406]:
# data filtration

In [407]:
x = np.array([12,-4,13,-11 ,6,8,9,5,-3,-1,-4,-8])

In [408]:
x

array([ 12,  -4,  13, -11,   6,   8,   9,   5,  -3,  -1,  -4,  -8])

In [410]:
x[x>0]

array([12, 13,  6,  8,  9,  5])

In [412]:
x[x%2==0]

array([12, -4,  6,  8, -4, -8])

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
df= pd.read_csv("../assects/HR_Analytics.csv")

In [12]:
null_col=df.isnull().sum()
null_col

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
Training

In [13]:
df_no_null= df.dropna(axis=0)

In [14]:
df_no_null.isnull().sum()

EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBa

In [17]:
print(df_no_null[df_no_null.duplicated()])

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
211   RM1468   27    26-35        No      Travel_Rarely        155   
328   RM1461   29    26-35        No      Travel_Rarely        468   
458   RM1464   31    26-35        No         Non-Travel        325   
655   RM1470   34    26-35        No       TravelRarely        628   
954   RM1463   39    36-45        No      Travel_Rarely        722   
1305  RM1469   49    46-55        No  Travel_Frequently       1023   
1336  RM1462   50    46-55       Yes      Travel_Rarely        410   

                  Department  DistanceFromHome  Education EducationField  ...  \
211   Research & Development                 4          3  Life Sciences  ...   
328   Research & Development                28          4        Medical  ...   
458   Research & Development                 5          3        Medical  ...   
655   Research & Development                 8          3        Medical  ...   
954                    Sales      

In [20]:
df_no_null[df_no_null["EmpID"] == "RM1469"]


EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate Department  \
1304  RM1469   49    46-55        No  Travel_Frequently       1023      Sales   
1305  RM1469   49    46-55        No  Travel_Frequently       1023      Sales   

      DistanceFromHome  Education EducationField  ...  \
1304                 2          3        Medical  ...   
1305                 2          3        Medical  ...   

      RelationshipSatisfaction  StandardHours  StockOptionLevel  \
1304                         4             80                 0   
1305                         4             80                 0   

     TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
1304                17                      3                2   
1305                17                      3                2   

      YearsAtCompany YearsInCurrentRole  YearsSinceLastPromotion  \
1304               9                  6                        0   
1305               9                  6                        0   

     YearsWithCurrManager  
1304                  8.0  
1305                  8.0  

[2 rows x 38 columns]

In [21]:
df_cleaned= df_no_null.drop_duplicates()

In [ ]:
df_cleaned.duplicated().sum()

np.int64(0)

In [24]:
df_cleaned.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [25]:

df_cleaned.to_csv('Hr_cleaned.csv', index=False)
